# Generated by Django 5.1.1 on 2024-09-19 15:51

import django.db.models.deletion
import django.utils.timezone
import user.mixins
import user.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.UUIDField(default=uuid.uuid4)),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name="Ім'я")),
                ('middle_name', models.CharField(blank=True, max_length=64, verbose_name='По батькові')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Призвище')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=user.models.user_path, verbose_name='Зображення')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Підтверджено')),
                ('creation_rules', models.BooleanField(default=True, verbose_name='Право створення')),
                ('comment_rules', models.BooleanField(default=False, verbose_name='Право коментування')),
                ('profile_view_rules', models.BooleanField(default=False, verbose_name='Право перегляду профілей')),
                ('show_email', models.BooleanField(default=False, verbose_name='Показувати ел.пошту')),
                ('show_phone', models.BooleanField(default=False, verbose_name='Показувати телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=(models.Model, user.mixins.ResizeImageMixin),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('show_birth_date', models.BooleanField(blank=True, null=True, verbose_name='Показувати дату народження')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Інформація')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.user')),
            ],
            options={
                'verbose_name': 'Користувачі > Профіль',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
    ]
